spring.application.name=EchoPlay
spring.datasource.url=jdbc:postgresql://localhost:5432/echo_play
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=metropol
spring.datasource.password=20002002
server.port=8081
aws.accessKey=AKIAJXJZ4N7ZJQ2V4Y2A
aws.secretKey=1p1pXH3qgV8Hs9t6Oj3nFm2dWl4v7u8y
aws.region=us-east-1